import Head from 'next/head'
import Image from 'next/image'
import Contact from '../components/Contact'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className='w-11/12 mx-auto'>
      <Head>
        <title>Next js with firebase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Contact />

    </div>
  )
}
